-- =========================================================
-- AwaraBanjara Production Migration: Trip Inquiries Table
-- Stores user trip inquiries with selected batch date, package/sub-package options, traveler count, and full trip details
-- Created: 2026-07-31
-- =========================================================

CREATE TABLE IF NOT EXISTS public.trip_inquiries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inquiry_id text UNIQUE NOT NULL,
    trip_id text NOT NULL,
    trip_title text NOT NULL,
    price text NOT NULL,
    selected_date text NOT NULL,
    selected_package text,
    selected_sub_package text,
    customer_name text NOT NULL,
    phone text NOT NULL,
    email text,
    travelers_count integer DEFAULT 1,
    message text,
    status text DEFAULT 'new',
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Safe ALTER TABLE statements to upgrade existing tables with missing columns
ALTER TABLE public.trip_inquiries ADD COLUMN IF NOT EXISTS inquiry_id text;
ALTER TABLE public.trip_inquiries ADD COLUMN IF NOT EXISTS trip_id text;
ALTER TABLE public.trip_inquiries ADD COLUMN IF NOT EXISTS trip_title text;
ALTER TABLE public.trip_inquiries ADD COLUMN IF NOT EXISTS price text;
ALTER TABLE public.trip_inquiries ADD COLUMN IF NOT EXISTS selected_date text;
ALTER TABLE public.trip_inquiries ADD COLUMN IF NOT EXISTS selected_package text;
ALTER TABLE public.trip_inquiries ADD COLUMN IF NOT EXISTS selected_sub_package text;
ALTER TABLE public.trip_inquiries ADD COLUMN IF NOT EXISTS customer_name text;
ALTER TABLE public.trip_inquiries ADD COLUMN IF NOT EXISTS phone text;
ALTER TABLE public.trip_inquiries ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE public.trip_inquiries ADD COLUMN IF NOT EXISTS travelers_count integer DEFAULT 1;
ALTER TABLE public.trip_inquiries ADD COLUMN IF NOT EXISTS message text;
ALTER TABLE public.trip_inquiries ADD COLUMN IF NOT EXISTS status text DEFAULT 'new';
ALTER TABLE public.trip_inquiries ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT timezone('utc'::text, now());

-- Enable Row Level Security (RLS)
ALTER TABLE public.trip_inquiries ENABLE ROW LEVEL SECURITY;

-- Create Public Access Policies
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public insert on trip_inquiries') THEN
        CREATE POLICY "Allow public insert on trip_inquiries" ON public.trip_inquiries FOR INSERT WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public select on trip_inquiries') THEN
        CREATE POLICY "Allow public select on trip_inquiries" ON public.trip_inquiries FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public delete on trip_inquiries') THEN
        CREATE POLICY "Allow public delete on trip_inquiries" ON public.trip_inquiries FOR DELETE USING (true);
    END IF;
END $$;

