-- =========================================================
-- AwaraBanjara Production Database Migration v2.0
-- Master Control Admin System (trips + site_config + feature flags)
-- Created: 2026-07-30
-- =========================================================

-- 1. Create trips table with full 24-macro schema & section flags
CREATE TABLE IF NOT EXISTS public.trips (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    title text NOT NULL,
    category text NOT NULL DEFAULT 'spiti_tours',
    duration text,
    price text,
    route text,
    tags text,
    image_url text,
    link text DEFAULT 'trip-detail.html',
    bento_img_1 text,
    bento_img_2 text,
    bento_img_3 text,
    bento_img_4 text,
    bento_img_5 text,
    about_text text,
    itinerary jsonb,
    inclusions jsonb,
    exclusions jsonb,
    package_options jsonb,
    sub_package_options text,
    departure_dates jsonb,
    faqs jsonb,
    reviews jsonb,
    reserve_banner_title text,
    reserve_banner_sub text,
    custom_quote_title text,
    custom_quote_sub text,
    whatsapp_number text,
    is_featured_reels boolean DEFAULT true,
    is_featured_stack boolean DEFAULT true,
    is_featured_lemonade boolean DEFAULT true,
    featured_order integer DEFAULT 0
);

-- Add missing columns to existing trips table if it already exists
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS is_featured_reels boolean DEFAULT true;
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS is_featured_stack boolean DEFAULT true;
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS is_featured_lemonade boolean DEFAULT true;
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS featured_order integer DEFAULT 0;

-- 2. Create site_config table for site-wide announcements, hero text, and contact numbers
CREATE TABLE IF NOT EXISTS public.site_config (
    key text PRIMARY KEY,
    value text NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Seed default site_config settings
INSERT INTO public.site_config (key, value) VALUES
    ('site_phone', '+91- 9103910523'),
    ('whatsapp_number', '+91-9103910523'),
    ('announcement_bar', '✨ Escape the ordinary — Explore handpicked Himalayan group trips!'),
    ('hero_headline', 'Awara Banjara'),
    ('hero_subtitle', 'Curated Himalayan Escapes, Motorbike Expeditions & Offbeat Group Trips')
ON CONFLICT (key) DO NOTHING;

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.trips ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_config ENABLE ROW LEVEL SECURITY;

-- Grant Full RLS Access Policies for Anonymous & Authenticated Users
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public select on trips') THEN
        CREATE POLICY "Allow public select on trips" ON public.trips FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public insert on trips') THEN
        CREATE POLICY "Allow public insert on trips" ON public.trips FOR INSERT WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public update on trips') THEN
        CREATE POLICY "Allow public update on trips" ON public.trips FOR UPDATE USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public delete on trips') THEN
        CREATE POLICY "Allow public delete on trips" ON public.trips FOR DELETE USING (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public select on site_config') THEN
        CREATE POLICY "Allow public select on site_config" ON public.site_config FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public insert on site_config') THEN
        CREATE POLICY "Allow public insert on site_config" ON public.site_config FOR INSERT WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public update on site_config') THEN
        CREATE POLICY "Allow public update on site_config" ON public.site_config FOR UPDATE USING (true);
    END IF;
END $$;

-- 4. Create Indexes
CREATE INDEX IF NOT EXISTS idx_trips_category ON public.trips(category);
