-- =========================================================
-- AwaraBanjara Production Migration: Fresh 33-Macro Table
-- Drops legacy columns/tables and recreates clean 33-macro trips table
-- Created: 2026-07-31
-- =========================================================

-- 1. Drop existing trips table and any legacy dependencies
DROP TABLE IF EXISTS public.trips CASCADE;

-- 2. Create fresh public.trips table with 33 explicit macro columns
CREATE TABLE public.trips (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    title text NOT NULL,
    category text NOT NULL DEFAULT 'spiti_tours',
    duration text NOT NULL,
    price text NOT NULL,
    route text,
    tags text,
    image_url text NOT NULL,
    link text DEFAULT 'trip-detail.html',
    bento_img_1 text,
    bento_img_2 text,
    bento_img_3 text,
    bento_img_4 text,
    bento_img_5 text,
    about_text text,
    itinerary jsonb DEFAULT '[]'::jsonb,
    inclusions jsonb DEFAULT '[]'::jsonb,
    exclusions jsonb DEFAULT '[]'::jsonb,
    package_options jsonb DEFAULT '[]'::jsonb,
    sub_package_options text DEFAULT 'none',
    departure_dates jsonb DEFAULT '[]'::jsonb,
    faqs jsonb DEFAULT '[]'::jsonb,
    reviews jsonb DEFAULT '[]'::jsonb,
    reserve_banner_title text DEFAULT 'Reserve Your Seat Now',
    reserve_banner_sub text DEFAULT 'Lock your batch seat with ₹1,000 token amount.',
    custom_quote_title text DEFAULT 'Private Custom Group Trip Available',
    custom_quote_sub text DEFAULT 'Customized dates and private vehicles available for groups of 4+ travelers.',
    whatsapp_number text DEFAULT '+91-9103910523',
    is_featured_reels boolean DEFAULT true,
    is_featured_stack boolean DEFAULT true,
    is_featured_lemonade boolean DEFAULT true,
    featured_order integer DEFAULT 0
);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.trips ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS Policies for Public Access (Anon & Authenticated)
CREATE POLICY "Allow public select on trips" ON public.trips FOR SELECT USING (true);
CREATE POLICY "Allow public insert on trips" ON public.trips FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on trips" ON public.trips FOR UPDATE USING (true);
CREATE POLICY "Allow public delete on trips" ON public.trips FOR DELETE USING (true);

-- 5. Create Performance Indexes
CREATE INDEX idx_trips_category ON public.trips(category);
CREATE INDEX idx_trips_featured ON public.trips(is_featured_reels, is_featured_stack, is_featured_lemonade);
