-- =========================================================
-- AwaraBanjara Production Database Migration v3.0
-- Table: public.trips (Clean 33-Macro Schema & RLS Policies)
-- Created: 2026-07-31
-- =========================================================

-- 1. Create trips table with full 33-macro schema
CREATE TABLE IF NOT EXISTS public.trips (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    title text NOT NULL,
    category text NOT NULL DEFAULT 'spiti_tours',
    duration text NOT NULL,
    price text NOT NULL,
    route text,
    tags text,
    image_url text NOT NULL,
    link text DEFAULT 'trip-detail.html',
    bento_img_1 text,
    bento_img_2 text,
    bento_img_3 text,
    bento_img_4 text,
    bento_img_5 text,
    about_text text,
    itinerary jsonb DEFAULT '[]'::jsonb,
    inclusions jsonb DEFAULT '[]'::jsonb,
    exclusions jsonb DEFAULT '[]'::jsonb,
    package_options jsonb DEFAULT '[]'::jsonb,
    sub_package_options text DEFAULT 'none',
    departure_dates jsonb DEFAULT '[]'::jsonb,
    faqs jsonb DEFAULT '[]'::jsonb,
    reviews jsonb DEFAULT '[]'::jsonb,
    reserve_banner_title text DEFAULT 'Reserve Your Seat Now',
    reserve_banner_sub text DEFAULT 'Lock your batch seat with ₹1,000 token amount.',
    custom_quote_title text DEFAULT 'Private Custom Group Trip Available',
    custom_quote_sub text DEFAULT 'Customized dates and private vehicles available for groups of 4+ travelers.',
    whatsapp_number text DEFAULT '+91-9103910523',
    is_featured_reels boolean DEFAULT true,
    is_featured_stack boolean DEFAULT true,
    is_featured_lemonade boolean DEFAULT true,
    featured_order integer DEFAULT 0
);

-- Ensure all columns exist on trips table
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS category text DEFAULT 'spiti_tours';
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS duration text;
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS price text;
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS route text;
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS tags text;
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS image_url text;
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS link text DEFAULT 'trip-detail.html';
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS bento_img_1 text;
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS bento_img_2 text;
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS bento_img_3 text;
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS bento_img_4 text;
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS bento_img_5 text;
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS about_text text;
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS itinerary jsonb DEFAULT '[]'::jsonb;
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS inclusions jsonb DEFAULT '[]'::jsonb;
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS exclusions jsonb DEFAULT '[]'::jsonb;
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS package_options jsonb DEFAULT '[]'::jsonb;
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS sub_package_options text DEFAULT 'none';
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS departure_dates jsonb DEFAULT '[]'::jsonb;
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS faqs jsonb DEFAULT '[]'::jsonb;
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS reviews jsonb DEFAULT '[]'::jsonb;
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS reserve_banner_title text;
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS reserve_banner_sub text;
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS custom_quote_title text;
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS custom_quote_sub text;
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS whatsapp_number text DEFAULT '+91-9103910523';
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS is_featured_reels boolean DEFAULT true;
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS is_featured_stack boolean DEFAULT true;
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS is_featured_lemonade boolean DEFAULT true;
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS featured_order integer DEFAULT 0;

-- Enable Row Level Security (RLS)
ALTER TABLE public.trips ENABLE ROW LEVEL SECURITY;

-- Grant Full RLS Access Policies for Anonymous & Authenticated Users
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public select on trips') THEN
        CREATE POLICY "Allow public select on trips" ON public.trips FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public insert on trips') THEN
        CREATE POLICY "Allow public insert on trips" ON public.trips FOR INSERT WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public update on trips') THEN
        CREATE POLICY "Allow public update on trips" ON public.trips FOR UPDATE USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public delete on trips') THEN
        CREATE POLICY "Allow public delete on trips" ON public.trips FOR DELETE USING (true);
    END IF;
END $$;

-- Create Indexes
CREATE INDEX IF NOT EXISTS idx_trips_category ON public.trips(category);
