-- =========================================================
-- AwaraBanjara Production Migration: Bookings Table
-- Stores user booking requests with selected batch date and traveler info
-- Created: 2026-07-31
-- =========================================================

CREATE TABLE IF NOT EXISTS public.bookings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id text UNIQUE NOT NULL,
    package_id text NOT NULL,
    customer_name text NOT NULL,
    email text NOT NULL,
    phone text NOT NULL,
    travelers_count integer DEFAULT 1,
    selected_batch text NOT NULL,
    selected_price text,
    special_requests text,
    status text DEFAULT 'pending',
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;

-- Create Public Access Policies
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public insert on bookings') THEN
        CREATE POLICY "Allow public insert on bookings" ON public.bookings FOR INSERT WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public select on bookings') THEN
        CREATE POLICY "Allow public select on bookings" ON public.bookings FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public delete on bookings') THEN
        CREATE POLICY "Allow public delete on bookings" ON public.bookings FOR DELETE USING (true);
    END IF;
END $$;
